<a href="https://colab.research.google.com/github/AtulMomre2327/Intro-to-Machine-Learning/blob/main/House_data_set_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/dataset_2.csv')

In [ ]:
df.head()

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
0,2473.192784,4.0,1992,Jaipur,Residential Lane,Furnished,Apartment,No,568486.0
1,2353.472711,4.0,2006,Indore,Corner Plot,Unfurnished,Apartment,Yes,577214.0
2,2212.222005,3.0,2012,Jaipur,Highway Facing,Semi-Furnished,Duplex,No,581300.0
3,2823.886596,6.0,1993,Lucknow,Main Road,Unfurnished,Villa,Yes,794614.0
4,1869.648721,5.0,2012,Jaipur,Corner Plot,Semi-Furnished,Apartment,No,493086.0

In [ ]:
df.describe()

          Area_SqFt        Rooms   Build_Year         Price
count   1091.000000  1091.000000  1124.000000  1.124000e+03
mean    2237.479473     4.568286  2005.080071  6.082015e+05
std      731.097828     1.678155    11.708876  1.431958e+05
min      700.000000     2.000000  1985.000000  2.486400e+05
25%     1834.022964     3.000000  1995.000000  5.161948e+05
50%     2201.545784     5.000000  2005.000000  6.025410e+05
75%     2576.139355     6.000000  2015.000000  6.895785e+05
max    10267.124330     7.000000  2024.000000  2.071402e+06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1124 entries, 0 to 1123
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Area_SqFt      1091 non-null   float64
 1   Rooms          1091 non-null   float64
 2   Build_Year     1124 non-null   int64
 3   Location       1124 non-null   object
 4   Street_Type    1124 non-null   object
 5   Furnishing     1091 non-null   object
 6   Property_Type  1124 non-null   object
 7   Has_Pool       1124 non-null   object
 8   Price          1124 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 79.2+ KB

In [ ]:
df.isnull().sum()

Area_SqFt        33
Rooms            33
Build_Year        0
Location          0
Street_Type       0
Furnishing       33
Property_Type     0
Has_Pool          0
Price             0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

Area_SqFt        0
Rooms            0
Build_Year       0
Location         0
Street_Type      0
Furnishing       0
Property_Type    0
Has_Pool         0
Price            0
dtype: int64

In [ ]:
df.shape

(1027, 9)

In [ ]:
# Column encoding
df = pd.get_dummies(df,columns = ['Location','Street_Type','Furnishing','Property_Type','Has_Pool'],drop_first = True)

In [ ]:
x = df.drop(columns =['Price'])
y = df['Price']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [ ]:
x_train.head()

,Area_SqFt,Rooms,Build_Year,Location_Gurugram,Location_Indore,Location_Jaipur,Location_Kanpur,Location_Lucknow,Location_Noida,Location_Prayagraj,Street_Type_Gated Society,Street_Type_Highway Facing,Street_Type_Main Road,Street_Type_Residential Lane,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Property_Type_Duplex,Property_Type_Independent House,Property_Type_Villa,Has_Pool_Yes
677,2503.537285,5.0,1992,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,False
290,2215.373300,6.0,1988,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,False,True
639,2417.689367,6.0,2020,False,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False
512,2151.575542,7.0,2013,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,False
709,2225.060135,4.0,1998,False,False,True,False,False,False,False,False,False,False,True,False,True,False,True,False,False

In [ ]:
y_train.head()

677    656681.0
290    562495.0
639    650928.0
512    652572.0
709    545932.0
Name: Price, dtype: float64

In [ ]:
x_test.head()

,Area_SqFt,Rooms,Build_Year,Location_Gurugram,Location_Indore,Location_Jaipur,Location_Kanpur,Location_Lucknow,Location_Noida,Location_Prayagraj,Street_Type_Gated Society,Street_Type_Highway Facing,Street_Type_Main Road,Street_Type_Residential Lane,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Property_Type_Duplex,Property_Type_Independent House,Property_Type_Villa,Has_Pool_Yes
469,1558.569158,7.0,2007,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False
580,2522.391190,5.0,2024,False,False,False,False,True,False,False,False,False,True,False,False,True,False,True,False,True
426,1415.491593,7.0,2007,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,True
115,1179.867808,7.0,1985,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True
464,1958.020398,5.0,1999,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False

In [ ]:
y_test.head()

469    423257.0
580    690207.0
426    454653.0
115    404564.0
464    605938.0
Name: Price, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
train_pred = model.predict(x_train)
print(train_pred)

[ 633806.63667472  557127.11036988  642566.12454386  652957.1866762
  527170.48727269  534982.72895957  524686.07695804  549155.77735384
  787715.51650521  768189.21409475  521851.75916999  700772.71754531
  472580.57431849  535107.20143487  564399.53346084  681675.938539
  643572.22219288  656972.88028354  800359.19441613  745840.66187211
  815667.77404678  724352.04542171  428031.4212174   576520.21569508
  897252.2934127   596604.64381756  501470.37595456  665640.54927285
  682834.62025907  792520.1624988   610959.5105231   635393.82393031
  503786.56745489  641460.47091913  762048.97373952  672659.47159672
  645738.39670566  429820.828679    559435.10946551  494111.01957882
  447524.18249112  489628.58257647  531760.17965209  488736.46678897
  619529.37654291  575120.57784423  557339.3208051   856828.91005163
  496639.02122566  555059.52546087  603815.31916816  500029.34392909
  688620.93563953  540734.76625956  505082.29260057  613975.67714383
  650126.82564188  728119.3553502   504926.1520991   525962.01559729
  548446.08135172  606442.97902798  634734.559572    618822.90491068
  472247.05069707  725200.66314935  410265.44808102  581275.99779428
  640887.35366913  546694.36800665  523471.72716162  492186.34960701
  758819.2260913   437531.78383271  635235.44813768  704110.53291168
  467598.06675188  639362.36759726 1381346.40483013  531532.19312423
  626848.30466556  659478.85976631  549784.19836621  611196.05915088
  535371.22794376  422908.85516243  612291.49148411  558545.00345343
  343657.91960409  584233.48570247  624140.1498367   561190.56214653
  701374.44615295  632018.18507858  619941.66696367  690381.1757376
  525634.57767808  536101.83155663  494743.29087686  782197.66798783
  450556.30850654  641189.942106    540555.43350586  491487.3899444
  625983.91614133  641319.45855149  591070.16248521  349189.7179933
  670256.99976415  480074.16230699  423050.15374795  642472.42025674
  694680.87420377  751116.58596176  806872.1551636   479159.73696139
 1582063.84280871  663960.8058042   845567.42473877  541694.78925289
  459024.90431055  427357.26061736  567104.30916869  550876.7297099
  586007.0906689   527782.03472602  585587.15025974  693781.80826428
  699623.33970702  459139.18724294  647353.78701575  692178.89487037
  594357.14918703  676662.2833497   589578.39377179  668880.888991
  453006.44829323  432304.46482835  540110.30757197  466657.61518139
  580906.1973497   413834.47431591  807251.70415468  680271.41888298
  650067.227989    736802.27545711  649524.72901244  623144.68787389
  574991.80388571  614239.58604422  500245.409893    618648.09543705
  618538.88425267  553687.75840151  730662.35226778  650348.01017597
  465547.06157188  429840.38680892  436051.14642633  775255.56250351
  559957.98962667  646063.70762464  588217.03571872  670586.31894833
  611971.44568147  513470.28606532  642802.97192308  374855.16579227
  505266.45709141  641746.34466484  719504.35960551  420039.28900119
  524718.73108575  386089.53221287  665551.30513445  462280.0416155
  853597.30885565  705722.65304895  538272.17867783  759835.42713129
  788127.10950048  686875.87211775  338354.76764102  414198.17288634
  450993.60734134  776795.0960915   687006.4367142   706382.87334777
  516471.4168585   682765.45392355  617488.67172587  735885.52994898
  603585.49999886  599526.82262577  412293.71955587  517864.57090337
  582792.84141026  713915.99568089  657308.59309597  643584.06340904
  610260.95138838  530044.13549826  822708.75816758  793824.60849509
  914605.29171581  549791.93458766  668120.54451883  638315.63212867
  362745.952021    459079.58672654  582995.46321008  583132.75132962
  654585.83798494  577797.81569372  400834.14938487  780453.00184502
  674036.72913378  664089.99337808  669831.17469624  568017.67367741
  472905.10971713  371175.3180859   657473.20589088  624837.73793921
  531874.9412295   592839.53847421  469294.48151861  541825.28296392
  630486.82263797  735209.31940251  636495.84754286  454541.90627896
  461464.07490179  503577.59980068  640156.28088945  594403.54591991
  624640.7747896   877008.93066967  445290.04275644  604606.98040271
  492471.47580297  720252.06206155  521949.43853925  791997.22569417
  552878.57250322  626108.31800096  716930.69107295  446593.41357331
  450401.11017413  790772.71528482  651668.03069653  626020.87478861
  550370.3876479   555752.83037657  729612.68024998  561960.50236067
  505144.24730571  560738.89783632  620135.17716554  629067.36782418
  568686.67867385  576556.8334365   579468.3796543   557713.13266333
  517736.97320491  687708.65085238  660563.60798259  751593.10138644
  586454.12843229  695937.91232249  480756.23579623  616483.13446323
  637557.01614134  656013.71250041  526377.34248019  528064.01468517
  716586.24131893  725125.63415836  543005.00076301  822085.72495769
  349501.67542638  616850.39681644  448725.63515572  818181.67671074
  650932.79548744  459143.1242103   616313.34959527  571664.26367004
  806782.66456715  636860.65212761  671559.12516847  596075.21077651
  535848.9640791   685326.39531842  571195.49045354  651916.30490743
  547663.88059319  594860.69268173  408424.11982359  816160.84088432
  581421.85242062  557912.74872809  690789.80173889  523061.78338275
 1727421.89399746  556206.87573391  685164.80676864  666202.38345003
  641061.87087469  836770.32157195  577953.92991629  636972.96134317
  766539.69949928  577828.46038633  844718.14318454  506230.49310508
  466381.87344022  681105.61118646  695488.56239427  519867.8130424
  571742.96521545  491769.51761077  727130.20545113  597835.66619265
  505334.05394158  430584.82044491  740356.47806675  473642.1954361
  531699.2274842   590003.3274724   716889.96403709  568591.6547666
  610536.67896584  296639.22427616  667022.33428617  703244.74578896
  588350.92257772  571967.75996889  807764.0042942   743329.86141826
  764953.40090576  366975.07104342  568235.34821051  600006.73775584
  633498.41071702  565153.69084459  651906.51941899  694312.09896097
  573690.92912042  551999.49328023  617495.65433513  409430.49859424
  856663.93663195  594518.74786861  458604.93979165  512860.69450422
  556062.42288456  733174.17089779  538343.11939958  678494.43040583
  590763.55859193  586725.17470509  565885.43775195  658791.28270349
  691239.92199769  609708.53800398  617184.66363291  616822.74249011
  620430.0888523   553491.66596436  740462.72226926  530035.07966679
  688242.90159103  817288.55970369  667167.79543363  767519.19214187
  562274.73711546  421100.97350814  444833.58824374  563954.5954642
  847962.8897708   640764.67194787  482443.93690961  583217.50359573
  704771.97229192  505222.91956323  705269.40002438  448247.34603509
  547563.38008126  686625.1716605   348997.1102064   536304.79154541
  693931.15460826  573469.78266233  553541.22098254  550943.57826547
  758951.63848218  479799.59173165  685836.80898094  605027.30088792
  699187.6684867   745566.6576215   536811.80216065  684148.66862136
  444698.51937401  527106.30449494  767748.24195621  598390.42273248
  650589.56657729  638811.32742478  624768.98963255  665175.29383916
  669083.28412181  503696.47911308  581518.65748851  778994.33386463
  566242.9042396   597047.79393713  528801.24676426  457394.96560203
  370386.06302335  558392.16957847  537017.71704779  712577.80925216
  597017.15914828  538523.40222801  648294.44919147  642379.42165422
  506875.09005743  701707.05215245  648105.29167751  778461.40546434
  659876.82884828  755598.07576001  693490.41043766  617459.88275548
  589081.2880342   503518.25270109  683513.88694067  905578.83444804
  583382.34767281  455462.72795313  484273.92177504  587196.51990941
  610609.93013296  651216.73427855 1107621.80915018  651916.37922174
  287760.08884586  812368.04857674  637590.17410161  699927.16228825
  605092.55567039  601835.82362858  568037.3324848   562958.9666929
  669245.29526848  543922.12286224  603801.5730154  2036894.6762038
  754051.68947674  704288.26212935  643715.81443737  720138.45177657
  629152.98460086  517318.03356761  271809.67127255  490521.10596305
  523466.85622958  496587.15352709  499401.2067942   595347.77090839
  527141.67078992  709290.80154221  781642.52913904  505323.85562172
  809360.40284876  517104.00156205  707627.22950788  730076.47901116
  520219.97733205  504822.10216735  592555.59954607  523455.94140603
  612657.97680928  645689.41365585  558404.90491256  524997.6372262
  546702.39698496  546587.997267    584067.17122751  500592.22561043
  483610.75545971  569791.395374    623293.47158291  832837.77422381
  650513.53220995  646713.57654693  694313.63611231  707988.63070237
  827937.65935002  593888.40581332  519248.28986669  543259.12028655
  674474.57133803  724814.25200099  815862.88107634  681012.60492392
  573185.06974569  661770.84772999  707867.04059385 1661769.32074028
  448469.96693955  695741.45196937  562434.59797211  691932.93665331
  361395.99587149  519605.84917769  593082.05994849  937396.8284766
  776880.9024273   631150.4296694   574407.9827198   710300.86282601
  550265.04048885  555989.00622887  430390.5207573   517915.62581202
  585042.61741867  502565.03135088  686086.60644315  710087.91471672
  606337.89381272  286330.95799569  738522.5357908   560439.22068055
  535596.58254534  682313.21751571  704213.19489777  691927.94018315
  518223.753455    507269.24867296  540284.79494023  627334.28543858
  518386.03248225  561452.19795308  447968.16715357  590421.16648647
  989168.80434901  497785.81090896  554578.55822776  540875.05758077
  487807.31615463  713421.07466895  425680.15129739  764495.77924985
  584959.97597382  489513.95092561  787061.47605364  641608.52763975
  542483.87936416  525608.58209369  579824.26574951  667072.42668843
  570838.30396824  853755.94722972  728161.24107347  456025.75592494
  863866.86158284  489415.99302099  677528.58545089  685473.73333243
  582867.21481376  610202.8042748   444988.23416906  557969.07176151
  428764.01372757  643619.58040526  507364.38774855  780945.27208441
  625621.89511106  667657.41092646  871387.24965162  661522.89051986
  514307.86778917  452455.07939742  637415.46898492  644663.36076647
  646209.8960688   479617.15920431  684548.45167428  694808.55140954
  475392.50127795  734205.93911207  685380.99603588  394601.18451128
  752683.6203683   524599.25432021  714915.38191658  609967.10025982
  515707.4892204   550171.09933368  526428.89113837  473979.37607453
  603459.1431836   661187.80932607  540735.33457938  566368.21110715
  618009.0273095   515397.0657111   694423.61814699  546735.65430701
  653830.92248521  628675.46234413  442365.44760442  655864.10433645
  777525.93267044  736580.53104076  726807.67018717  741045.38244072
  687158.50879923  834207.33934033  594861.53860138  398956.11025789
  565455.05834986  803097.96033103  694723.11375057  812746.2327735
  733795.24861835  721632.43172513  579831.24371466  621522.31857984
  594386.58673273  612303.87724879  685045.34810689  777202.17371787
  535861.40312004  509209.89247299  686408.73358132  577004.63024122
  602825.90767409  651754.07783293  873009.96569435  541310.82318537
  727207.47443302  846747.68855869  431173.98427108  524180.07571635
  544103.68695475  603446.34861342  459759.55003593  478369.69445085
  585427.22249981  805538.37358457  506037.77758801  381014.16332549
  628285.26190784  499885.93539885  419022.10585902  524935.46667904
  447251.52444627  500181.73479003  712467.9264907   544194.04930742
  432616.0325038   374288.09914316  674932.08538046  514755.99119043
  508682.7970636   621472.68576278  400069.8117636   449892.04439842
  664222.52511048  394273.1770311   660969.01055084  649091.47855012
  656186.28077217  451427.20260599  674530.22643644  684364.34212676
  452107.16748161  594897.7884643   460273.99057743  639543.78471298
  716060.37685434  607921.87969911  678256.45391849  742088.00107699
  559819.98951633  695080.6689445   598856.65255105  698861.88435324
  488729.23042995  561218.50180001  682715.05759231  430328.54105871
  596766.58122949  554676.83978192  603733.80074982  701364.98879193
  502566.21826135  460061.34965896  736964.73721231  622671.99425477
  710659.20499789  721026.28570144  677444.81134361  748515.80053225
  569753.18735532  595421.83762113  580953.16597593  692403.19726704
  836518.16136053  555131.3632864   591830.37529405  476223.68867382
  661778.98101881  545964.74628223  471007.44464431  557249.55446608
  443870.94676129  795048.39982232  639499.79887159  634026.76586541
  921266.39916002  340627.30180332  454337.51714617  576449.63628339
  486731.83461903  715047.55074814  623878.03556648  622817.46129634
  517033.37518943  544532.25773976  484076.90968208  423562.49339613
  590657.47512786  554715.75252296  543983.40355734  609032.59962939
  516577.25389738  529087.36981744  603075.32524038  699367.67064496
  665626.52181497  525377.92006045  514109.00910534  573389.81049954
  531761.65972359  521939.96772007  361920.00656881  312825.23511577
  405103.07294283  712429.45232821  460579.76892355  561170.6797778
  561301.11576927  697197.5303715   608928.06720616  621033.98510306
  532994.24641244  733283.94728217  544630.84278325  398093.06753786
  643901.6217397   511887.02342959  613075.94752679  663313.52575809
  594729.49733968  705800.79365873  761055.28191436  766100.19695796
  678369.95354533  822172.44899901  738253.31705009  479910.9995408
  604537.10749403  746130.44150475  615411.22526586  388636.83305163
  542064.26987969 1107512.58130843  720082.84255027  795738.90932058
  578327.78187758  567798.69943528  674913.39963672  645434.1182326
  738734.40975397  803657.2566298   645222.68259266  540450.81110114
  691854.77542004  625701.57131881  487492.87682008  688032.79615897
  518832.46542209  709365.28297957  872572.76554318  749713.30918624
  826196.41754108  347025.23225126  613599.62346075  640819.58565132
  657373.95151155  504748.47580948  517011.21588128  464482.79516472
  636507.97356043  703184.80868866  694554.38344808  466946.9844832
  670012.34869437  488344.83276278  338803.94226501  577692.82665129
  620123.59153749  634292.46837702  800526.65883819  743956.97435511
  597158.883784  ]

In [ ]:
test_pred = model.predict(x_test)
print(test_pred)

[ 469536.05833049  697169.17749953  446700.48403528  443099.15566653
  603669.0237335   694851.52899235  656336.92019561  547244.0410703
  672507.40775646  511516.40283701  719245.33900725  543949.98379726
  601803.9195776   409482.17238737  301146.06170519  729824.73100502
  725417.6881408   512010.56198489  494729.4635404   498209.40724955
  633305.50645088  781403.90050173  764089.90327165  633790.16059885
  711439.41333812  535883.38247296  571799.32812315  768496.24463039
  643622.9798736   672224.41554833  768546.42582163  611491.12595025
  636335.24640791  445951.35241356  351831.22878606 1254440.36855393
  824978.23268635  670594.17022842  629726.31260479  619384.43325281
  762505.63476191  517759.85237952  668175.66128066  425261.09911659
  528603.1197231   615371.74595583  465547.04898269  635677.60469216
  542717.54554189  708678.16919715  375299.76292118  680935.77463613
  581784.8679595   512864.38752027  628891.11817387  475128.65752756
  774725.82403048  433108.63019     723218.85688844  633718.13279611
  613150.68362352  729114.73314501  577094.02158437  751848.10836406
  464150.80250774  484376.56950837  503910.54855988  605695.65365526
  590157.38036099  823554.25579408  701931.00317835  754288.25631482
  559085.35223874  896356.73251827  562605.45562002  683974.42652625
  730939.57670402  543474.4995084   509446.55043363  676581.10984975
  793757.82421063  555938.33620619  576835.87294915  797479.41651784
  652897.67405136  700519.76279741  609214.5162149   419588.96960744
  640382.52342626  648790.48585282  741075.81955744  642946.37242357
  513938.76164814  618855.60354047  628380.45628572  465495.93026473
  500161.58712828  512406.18167501  778713.33990391  703935.31868743
  744061.8491066   419066.16396234  547388.34148311  739587.78805757
  477236.87054858  868374.81064228  641303.56090246  491075.72143526
  931062.66515417  445495.66555565  635517.36553184  543920.69664595
  555932.79754786  702239.23477428  395688.01772314  663357.18764024
  604744.00080894  711802.62628597  504269.88609896  600035.05584622
  528769.43936672  590269.10658441  524738.86089332  775310.54858872
  586173.22905895  661623.20577115  401562.86536228  614176.52226165
  617844.09234592  692746.56044096  736463.65429411  598399.25455314
  584961.89491163  631584.22929154  450509.08569864  510284.4216128
  393365.45941155  446678.82645956  534975.49039345  534050.87659557
  684775.67504056  636508.60774039  649759.51656329  645221.3637297
  652290.70560919  531668.6927724   591530.39353278  600032.07991553
  616383.59970476  549465.98135358  658341.14874185  457904.93420049
  597337.12095744  341157.21636859  652431.9967958   729291.61268724
  492133.18482249  470832.92228266  651043.94813101  732659.68521271
  502895.73459843  559710.98322851  541037.25750668  695519.78440075
  514419.66794576  715112.02316471  648457.77010375  779165.38561442
  527450.2070983   493929.30560666  650797.28663831  485635.40243016
  629438.97682095  689258.96245676  719421.89268834  679093.34649195
  688784.50117071  712674.69000794  646114.95388826  461653.13234044
  778087.44187715  595683.64799228  585456.92118043  529230.46354961
  515161.11104516  657228.635124    573493.76578351  507374.05967535
  551574.29055128  697585.95924494  613122.67106397  509978.21205122
  556984.85918739  644018.97469459  576990.03405576  454463.80530164
  800135.02494502  614247.50209582  570181.75181947  607631.4793247
  557404.38342071  701427.28130723  393190.03491654  411984.45908314
  612643.62348555  623292.44867899]

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [ ]:
print('Train mean_squared_error :-',mean_squared_error(y_train,train_pred))
print('Train mean_absolute_error :-',mean_absolute_error(y_train,train_pred))
print('Train mean_absolute_percentage_error :-',mean_absolute_percentage_error(y_train,train_pred)*100)
print('Train R2 score ',r2_score(y_train,train_pred))

Train mean_squared_error :- 946924570.4490764
Train mean_absolute_error :- 18390.575310728
Train mean_absolute_percentage_error :- 3.0150194155467767
Train R2 score  0.9568602562021604

In [ ]:
print('Test mean_squared_error :- ',mean_squared_error(y_test,test_pred))
print('Test mean_absolute_error :-',mean_absolute_error(y_test,test_pred))
print('Test mean_absolute_percentage_error :-',mean_absolute_percentage_error(y_test,test_pred)*100)
print('Test R2 score ',r2_score(y_test,test_pred))

Test mean_squared_error :-  515916154.351647
Test mean_absolute_error :- 18429.112798823342
Test mean_absolute_percentage_error :- 3.2873272512118143
Test R2 score  0.9701944738745564